package main

// Declare a global map variable
var Data = map[string]interface{}{
	"accountid":       "XP67739",
	"buy_avg":         3205.3,
	"buy_qty":         1,
	"buy_val":         3205.3,
	"cf_buy_avg":      0,
	"cf_buy_qty":      0,
	"cf_net_qty":      0,
	"cf_sell_avg":     0,
	"cf_sell_qty":     0,
	"day_buy_avg":     3205.3,
	"day_buy_qty":     1,
	"day_buy_val":     3205.3,
	"day_net_qty":     0,
	"day_sell_avg":    3205.3,
	"day_sell_qty":    1,
	"day_sell_val":    3205.3,
	"exchange":        10,
	"fy_token":        "10100000001348",
	"id":              "NSE:HEROMOTOCO-EQ-INTRADAY",
	"instrument":      0,
	"lot_size":        1,
	"net_avg":         0,
	"net_qty":         0,
	"oms_flag":        "K:1",
	"precision":       2,
	"price_multiplier": 1,
	"product_type":    "INTRADAY",
	"qty":             0,
	"qty_multiplier":   1,
	"rbirefrate":      1,
	"segment":         10,
	"sell_avg":        3205.3,
	"sell_qty":        1,
	"sell_val":        3205.3,
	"symbol":          "NSE:HEROMOTOCO-EQ",
	"symbol_desc":     "HERO MOTOCORP LIMITED",
	"symbol_exch":     "HEROMOTOCO",
	"tick_size":       0.05,
	"tran_side":       0,
}